<?php
/**
 * Created by PhpStorm.
 * User: Gong
 * Date: 2018/9/22
 * Time: 8:01
 */

namespace App\HttpController\Path;
use EasySwoole\Core\Http\AbstractInterface\Controller;
class Index extends Controller
{
    function index()
    {
        // TODO: Implement index() method.
        $this->actionNotFound('index');
    }
    protected function onRequest($action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }
    /*
     * /path/a/1-1-1-1.html
     */
    public function a()
    {
        var_dump($this->request()->getUri()->getPath());
    }
}