<?php
/**
 * Created by PhpStorm.
 * User: flanche
 * Date: 2018/9/21
 * Time: 23:54
 */

namespace App\HttpController;
use EasySwoole\Config;
use EasySwoole\Core\Component\Di;
use EasySwoole\Core\Component\Logger;
use EasySwoole\Core\Http\Request;
use EasySwoole\Core\Http\Response;
use EasyWeChat\Factory;
use EasyWeChat\Kernel\Exceptions\DecryptException;
use App\Utility\Tools;
use App\Model\Profile;
use Illuminate\Database\Capsule\Manager as Capsule;
use WeMini\Crypt;
use App\Model\Visitors;
use App\Model\Redpack;
class Index extends Base
{
    public function index()
    {
        $this->response()->write('Hello easySwoole!');
        $this->writeJson(200,'支付成功','success');
        parent::index(); // TODO: Change the autogenerated stub
        $this->onException('index');
    }

}